language: java

jdk:
  - oraclejdk7

script: mvn -Dgpg.skip=true install

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SiJm46QrEHRorVsB5U6F0rcudtOlDBdWx8okQGLxgos4cNdO3Apni8bsjNKC9m9X4fNKKK8C53W2J4xRnpj2nj1wJWlYxgJW/ONITXNxiB+ylz3V6uyxDazydJOIorU1ILHwb3xAu8ylfPtEvFMpTOXrtiSzjFqQ3Ewsya3BXHs="

addons:
  coverity_scan:
    project:
      name: "zolyfarkas/spf4j"
      description: "Build submitted via Travis CI"
    notification_email: zolyfarkas@yahoo.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true -Dgpg.skip=true compile"
    branch_pattern: master


